// ============================================================================
// ClearanceRTIPublisher.h - CLEARANCE's RTI Connext DDS publisher API.
//
// Sibling to FClearancePublisher in ClearanceDDS. Same public-API shape,
// same six-topic schema, same POD semantics - just bound against RTI's
// commercial Connext runtime instead of eProsima Fast DDS. The two
// implementations can run simultaneously in the same process on different
// domain IDs (default: Fast DDS on domain 0, RTI on domain 1) so a
// federation observer sees the same six data primitives on both DDS
// runtimes plus the DIS legacy wire.
//
// Types come from the module-private AirspaceTelemetry.hpp generated by
// rtiddsgen. Same IDL text as ClearanceDDS, but declared in
// namespace ClearanceRTI so the two generated type sets don't collide
// if both DDS headers ever end up in the same translation unit.
//
// Public API is pure C++, engine-free. RTI runtime types are hidden
// behind FClearanceRTIPublisher's PImpl. - TripleA
// ============================================================================

#pragma once

#include "CoreMinimal.h"                     // for THIRD_PARTY_INCLUDES_START/END
#include "ClearanceRTI/ClearanceRTIExport.h"

// RTI's generated headers pull in <windows.h> transitively, which defines
// macros like UpdateResource -> UpdateResourceW that then poison every
// downstream UE header that uses those names (UTextureRenderTarget2D
// among many). UE's THIRD_PARTY_INCLUDES_START / END wrap the include
// with Windows push/pop and a warnings-off scope so the RTI headers
// parse without leaking macros into engine code. - TripleA
//
// Filename is intentionally distinct from ClearanceDDS's AirspaceTelemetry.hpp
// so both generated headers can coexist in a translation unit that pulls in
// the DDS AND the RTI adapter (which the ClearanceSim unity build does).
// Otherwise the identical filename collides and only one namespace's types
// resolve. - TripleA
#include "Windows/AllowWindowsPlatformTypes.h"
THIRD_PARTY_INCLUDES_START
#include "AirspaceTelemetryRTI.hpp"
THIRD_PARTY_INCLUDES_END
#include "Windows/HideWindowsPlatformTypes.h"

#include <cstdint>
#include <memory>

namespace ClearanceRTI
{
	// Forward declaration - the impl body lives in ClearanceRTIPublisher.cpp
	// so RTI headers don't leak through the public API. - TripleA
	class FClearanceRTIPublisherImpl;

	class CLEARANCERTI_API FClearanceRTIPublisher
	{
	public:
		// Create the participant + all six writers on the given DDS domain.
		// Returns nullptr on any RTI initialisation failure. Default domain
		// is 1 to sit next to Fast DDS (which defaults to 0) so both
		// runtimes can coexist in the same process without stepping on
		// each other's discovery traffic. - TripleA
		static std::unique_ptr<FClearanceRTIPublisher> Create(std::uint32_t DomainId = 1);
		~FClearanceRTIPublisher();

		FClearanceRTIPublisher(const FClearanceRTIPublisher&) = delete;
		FClearanceRTIPublisher& operator=(const FClearanceRTIPublisher&) = delete;

		// Publish one instance of each topic. Returns true if the DataWriter
		// accepted the sample. Non-blocking - if the send buffer is full the
		// sample is dropped (matches DIS best-effort semantics). - TripleA
		bool PublishAircraftState   (const AircraftState& S);
		bool PublishFireEvent       (const FireEvent& E);
		bool PublishDetonationEvent (const DetonationEvent& E);
		bool PublishEmissionSnapshot(const EmissionSnapshot& S);
		bool PublishTransmitterState(const TransmitterState& T);
		bool PublishSignalEvent     (const SignalEvent& E);

		// Total samples successfully accepted by any DataWriter since
		// creation. Drives the RTI FEDERATION panel's rate + count UI. - TripleA
		std::uint64_t GetTotalPublishedCount() const;

		// Diagnostic hook - when Create() returns nullptr, call this on a
		// throwaway instance to pull the last RTI exception text. Empty
		// string when nothing failed. Useful for surfacing license
		// expiry or missing type-plugin registration to the log. - TripleA
		static std::string GetLastCreateError();

	private:
		FClearanceRTIPublisher();
		std::unique_ptr<FClearanceRTIPublisherImpl> Impl;
	};
}
